### PR TITLE
Merge changes from Mr-Dave Master

### PR DESCRIPTION
**Pull request by Mr-Dave**
This is obviously a massive pull.  Various bugs and associated fixes were implemented throughout the development process of my fork and illustrated in the changes below.  It may be easier to review the end result rather than the step by step evolution.  As far as I can determine, this pull would resolve all the outstanding rtsp issues listed in your fork.

### CODE REVIEW

**Comment by tosiara** [comment]
I also vote for this pull. Tested it a lot, have been running stable for long time

**Comment by aklomp** [comment]
Congratulations on shipping this massive amount of work, but `048791e` appears to include my Pull #20 with my commit message squashed.

**Comment by Mr-Dave** [comment]
All changes were not properly attributed.

**Comment by aklomp** [comment]
No need to close this pull request and lose all the comments, you can force-push over the existing pull request (your master branch), and this request will update automatically.

**Comment by tosiara** [comment]
What was the purpose of all those rebase, revert and recommit? Now it just a little more mess in repo. The fork was ready to auto merge without any conflicts. @aklomp 's commit has now been removed from @Mr-Dave 's fork - why? I'm really confused now

**Comment by aklomp** [comment]
About the rebase: I was noting that this pull request integrated a number of other pull requests without merging them in properly. Although the codebase gets the improvements, it removes the attribution, commit messages, and history associated with those pulls. It also obscures which pull requests are dependent on each other, making it it harder for the maintainer to decide on an individual basis which to apply, and in which order. I suggested a few methods to resolve this in the comments of Issue #20. Best thing, I think, would be for the maintainer to merge the issues one by one in order of dependence.

I have no strong feelings about this, my point was to make a housekeeping comment. It was not my intention to get my work removed from Mr-Dave's tree, but rather to have it merged properly.

I applaud the massive work Mr-Dave has done (and, importantly, shipped), so feel free on my part to reopen this pull request as it was.

**Comment by Mr-Dave** [comment]
Aklomp indicated that my fork and associated merge did not provide 
proper attribution of his work.  In order to make sure that Aklomp gets 
proper attribution for his work, I rebased the files affected by his 
work within my fork.  Therefore, if my fork is merged into the master, 
there will not be any conflicts with his pull request. As an 
alternative, he can issue a pull request to my fork and if my fork is 
merged, it would include his attribution that way.

Dave

**Pull request closed without merging**
